### ISSUE TITLE
Vermeidung von Redundanzen im Code durch Nutzung der Standarddateien

### ISSUE THREAD

**Issue by moewew** [domhardt/BibLaTeX-DIN1505#1]
Beim Betrachten des Codes ist mir aufgefallen, dass einige recht lange Code-Portionen eins zu eins dem Code aus `biblatex`s Standardstilen entsprechen. Um Deinen Code kürzer und übersichtlicher zu halten, kannst Du `\RequireCitationStyle` und `\RequireBibliographyStyle` nutzen. Deine `din.cbx` würde sich so von fast 130 Zeilen zu etwa 10 Zeilen reduzieren lassen.

Eigentlich bräuchtest Du dann nur

```
\ProvidesFile{din.cbx}
[\abx@cbxid $Id: din.cbx, v2012-05-29, Michael Domhardt $]

\RequireCitationStyle{authoryear}
\renewcommand*{\nameyeardelim}{\addspace}
\renewcommand*{\multinamedelim}{\addnbthinspace \& \addthinspace}
\renewcommand*{\finalnamedelim}{\multinamedelim}
```

Mit eventuell ein paar Anpassungen zu `textcite`. Da sind noch ein paar kleine Unterschiede, ich weiß aber nicht, ob das vielleicht daran liegt, dass Du eine etwas ältere Version als Grundlage genutzt hast. (Wenn Du oben zusätzlich `\renewcommand*{\textcitedelim}{\multicitedelim}` hinzufügst, bekommst Du exakt dieselbe Ausgabe wie mit der aktuellen `din.cbx`; aber vielleicht gefällt Dir die neue Ausgabe ja auch, es ist schließlich ein `\textcite`.)

In `din.bbx` sind die Abweichungen von `standard.bbx` schon größer, aber auch hier kann es sich lohnen, auf `\RequireBibliographyStyle{standard}` zurückzugreifen. Änderungen sehe ich vor Allem bei den `@in*`-Typen, da müsste man wohl in den sauren Apfel beißen und die Treiber im Code haben.

Für die Klammern um den Herausgeber, sollte eigentlich  `\DeclareFieldFormat{editortype}{\mkbibparens{#1}}` ausreichen, es ist nicht notwendig, `editor+othersstrg` und `editorstrg` umzudefinieren.

Bei `\DeclareFieldFormat[article]{number}{Nr. #1\midsentence}` würde ich `\bibstring{number}` oder, wenn es immer die kurze Version sein muss `\bibsstring{number}` nutzen: `\DeclareFieldFormat[article]{number}{bibstring{number}~#1\midsentence}`. Ob das ganze `\midsentence` notwendig ist, bin ich mir nicht so ganz sicher.

Für `\renewcommand*{\multinamedelim}{\mbox{ }\addspace\addsemicolon\addspace}%` gibt es auch noch andere Lösungen http://tex.stackexchange.com/q/130448/35864.

Ein Stil kann sicherlich auch den Punkt erreichen, ab dem es sich lohnt, alles komplett selbst zu schreiben (man denke an `biblatex-apa`, `biblatex-chicago`, `biblatex-philosophy`). Dadurch sind bei Änderungen in `biblatex` weniger Anpassungen erforderlich. Allerdings werden Änderungen auch automatisch vererbt. Eine kurze Diskussion von beiden Ansätzen kannst Du in http://texwelt.de/blog/modifizieren-eines-biblatex-stils/ finden.
Bei Deinem Projekt kann ich aber definitiv noch die Vorteile von `\RequireCitationStyle` und `\RequireBibliographyStyle` sehen (auf jeden Fall für die `.cbx`).

**Comment by moewew** [comment]
Die `din.bbx` konnte ich mit den Methoden von oben von knapp 1000 Zeilen auf etwa 300 Zeilen reduzieren. Der Löwenanteil der dreihundert verbliebenen Zeilen wird dabei von den Kopien der Treiber für `@inbook`, `@incollection` und `@inproceedings` sowie die Neudefinition von `@standard` benötigt. Durch die Nutzung des Paketes `xpatch` könnte man für die ersten drei noch eine andere Lösung finden.

**Comment by domhardt** [comment]
Bitte entschuldige die späte Antwort. Ich hatte bereits befürchtet, dass meine Lösung nicht optimal ist. Immerhin ist es nur eine Modifikation des Standard-Stils. Ich bin für jeden Hinweis und jede Unterstützung dankbar. Kannst Du mir Deine Änderungen zur Verfügung stellen?

Ich schreibe gerade meine Dissertation und verwende dabei auch diesen Stil. Mir sind auch noch ein paar andere Probleme (neuer Issue) aufgefallen, um die ich mich aber erst kümmern kann, wenn die Diss bei meinem Prof zum letzten Review vor der Abgabe liegt. Ich hoffe, dass ich in der Zeit von Dez. 15 bis Feb. 16 dazu komme.

**Comment by moewew** [comment]
Bei der `.cbx` bin ich bei

```
\ProvidesFile{din-neu.cbx}[2015/09/06, v2015-09-06, DIN 1505 style for biblatex, Michael Domhardt]

\RequireCitationStyle{authoryear}
\renewcommand*{\nameyeardelim}{\addspace}
\renewcommand*{\multinamedelim}{\addnbthinspace \& \addthinspace}
\renewcommand*{\finalnamedelim}{\addnbthinspace \& \addthinspace}

\renewcommand*{\textcitedelim}{\multicitedelim}

\endinput
```

angelangt.

Die `.bbx` ist noch etwas länger

```
\ProvidesFile{din-neu.bbx}[2015/09/06, v2015-09-06, DIN 1505 style for biblatex, Michael Domhardt]

\RequireBibliographyStyle{standard}


\setlength{\bibhang}{0em}% hängender Einzug der Bibliografie
%\setlength{\bibitemsep}{\baselineskip}% Abstand zwischen zwei Einträgen im Literaturverzeichnis
\setlength{\bibinitsep}{\baselineskip}% Abstand zwischen zwei unterschiedlichen Anfangsbuchstaben im Literaturverzeichnis

\renewcommand*{\labelnamepunct}{\addcolon\addspace}% nach den Autoren- und Herausgebernamen folgt ein Doppelpunkt

\DeclareNameAlias{default}{last-first}% Nachnamen stehen bei Autoren und Herausgebern vor dem Vorname 

\DeclareFieldFormat[article]{title}{#1\midsentence}% keine Anführungszeichen beim Titel von Zeitschriftenbeiträgen
%\DeclareFieldFormat[article]{date}{(#1)\midsentence}% Klammern um das Jahr bei Zeitschriftenbeiträgen
\DeclareFieldFormat[article]{number}{Nr. #1\midsentence}% Klammern um das Jahr bei Zeitschriftenbeiträgen

\DeclareFieldFormat[incollection]{title}{#1\midsentence}% keine Anführungszeichen beim Beiträgen in Sammelwerken

\DeclareFieldFormat[inproceedings]{title}{#1\midsentence}% keine Anführungszeichen beim Titel von Konferenzbeiträgen

\DeclareFieldFormat[inbook]{title}{#1\midsentence}% keine Anführungszeichen beim Titel von Buchbeiträgen

\DeclareFieldFormat[thesis]{title}{\mkbibemph{#1}\midsentence}% keine Anführungszeichen dafür kursiver Titel bei Dissertationen


\renewcommand*{\finentrypunct}{}% Punkt am Ende der Publikation entfernen


\DeclareFieldFormat{editortype}{\mkbibparens{#1}}

\renewcommand*{\multinamedelim}{\addsemicolon\space}
\renewcommand*{\finalnamedelim}{\addsemicolon\space}

\renewbibmacro*{editor}{% Komma vor Herausgeberkürzel entfernen
  \ifboolexpr{
    test \ifuseeditor
    and
    not test {\ifnameundef{editor}}
  }
    {\printnames{editor}%
    \setunit{\space}% <- hier
    \usebibmacro{editorstrg}%
     \clearname{editor}}
    {}}

\renewbibmacro*{editor+others}{% Komma vor Herausgeberkürzel entfernen
  \ifboolexpr{
    test \ifuseeditor
    and
    not test {\ifnameundef{editor}}
  }
    {\printnames{editor}%
     \setunit{\space}% <- hier
     \usebibmacro{editor+othersstrg}%
     \clearname{editor}}
    {}}

\AtBeginBibliography{% 
  \renewcommand*{\mkbibnamelast}[1]{\textsc{#1}}% Nachnamen bei Autoren und Herausgebern in Kapitälchen
  \renewcommand*{\multinamedelim}{\mbox{ }\addspace\addsemicolon\addspace}%  Spatium und Semikolon als Autoren- und Herausgebertrenner
  \renewcommand*{\finalnamedelim}{\multinamedelim}%  Spatium und Semikolon als Autoren- und Herausgebertrenner
  }

% zusätzlicher Eintragstyp @standard
% geändert von @misc
\DeclareBibliographyDriver{standard}{%
  \usebibmacro{bibindex}%
  \usebibmacro{begentry}%
  \usebibmacro{series+number}% Nummer zuerst
  \setunit{\labelnamepunct}\newblock
  \usebibmacro{title}%
  \newunit
  \printlist{language}%
  \newunit\newblock
  \usebibmacro{byauthor}%
  \newunit\newblock
  \usebibmacro{byeditor+others}%
  \newunit\newblock
  \printfield{howpublished}%
  \newunit\newblock
  \printfield{type}%
  \newunit
  \printfield{version}%
  \newunit
  \printfield{note}%
  \newunit\newblock
  \usebibmacro{organization+location+date}%
  \newunit\newblock
  \usebibmacro{doi+eprint+url}%
  \newunit\newblock
  \usebibmacro{addendum+pubstate}%
  \setunit{\bibpagerefpunct}\newblock
  \usebibmacro{pageref}%
  \newunit\newblock
  \iftoggle{bbx:related}
    {\usebibmacro{related:init}%
     \usebibmacro{related}}
    {}%
  \usebibmacro{finentry}}

\DeclareBibliographyDriver{inbook}{%
  \usebibmacro{bibindex}%
  \usebibmacro{begentry}%
  \usebibmacro{author/translator+others}%
  \setunit{\labelnamepunct}\newblock
  \usebibmacro{title}%
  \newunit
  \printlist{language}%
  \newunit\newblock
  \usebibmacro{byauthor}%
  \newunit\newblock
  \usebibmacro{in:}%
  \usebibmacro{bybookauthor}%
  \newunit\newblock
  \usebibmacro{editor+others}% Herausgeber (Hrsg.) statt hrsg. von Herausgeber
  \setunit{\labelnamepunct}\newblock%
  \usebibmacro{maintitle+booktitle}%
  \newunit\newblock
%  \usebibmacro{byeditor+others}%
%  \newunit\newblock
  \printfield{edition}%
  \newunit
  \iffieldundef{maintitle}
    {\printfield{volume}%
     \printfield{part}}
    {}%
  \newunit
  \printfield{volumes}%
  \newunit\newblock
  \usebibmacro{series+number}%
  \newunit\newblock
  \printfield{note}%
  \newunit\newblock
  \usebibmacro{publisher+location+date}%
  \newunit\newblock
  \usebibmacro{chapter+pages}%
  \newunit\newblock
  \iftoggle{bbx:isbn}
    {\printfield{isbn}}
    {}%
  \newunit\newblock
  \usebibmacro{doi+eprint+url}%
  \newunit\newblock
  \usebibmacro{addendum+pubstate}%
  \setunit{\bibpagerefpunct}\newblock
  \usebibmacro{pageref}%
  \newunit\newblock
  \iftoggle{bbx:related}
    {\usebibmacro{related:init}%
     \usebibmacro{related}}
    {}%
  \usebibmacro{finentry}}


\DeclareBibliographyDriver{incollection}{%
  \usebibmacro{bibindex}%
  \usebibmacro{begentry}%
  \usebibmacro{author/translator+others}%
  \setunit{\labelnamepunct}\newblock
  \usebibmacro{title}%
  \printlist{language}%
  \usebibmacro{in:}%
  \usebibmacro{editor+others}% Herausgeber (Hrsg.) statt hrsg. von Herausgeber
  \setunit{\labelnamepunct}\newblock%
  \usebibmacro{maintitle+booktitle}%
  \newunit\newblock
  \printfield{edition}%
  \newunit
  \iffieldundef{maintitle}
    {\printfield{volume}%
     \printfield{part}}
    {}%
  \newunit
  \printfield{volumes}%
  \newunit\newblock
  \usebibmacro{series+number}%
  \newunit\newblock
  \printfield{note}%
  \newunit\newblock
  \usebibmacro{publisher+location+date}%
  \newunit\newblock
  \usebibmacro{chapter+pages}%
  \newunit\newblock
  \iftoggle{bbx:isbn}
    {\printfield{isbn}}
    {}%
  \newunit\newblock
  \usebibmacro{doi+eprint+url}%
  \newunit\newblock
  \usebibmacro{addendum+pubstate}%
  \setunit{\bibpagerefpunct}\newblock
  \usebibmacro{pageref}%
  \newunit\newblock
  \iftoggle{bbx:related}
    {\usebibmacro{related:init}%
     \usebibmacro{related}}
    {}%
  \usebibmacro{finentry}}

\DeclareBibliographyDriver{inproceedings}{%
  \usebibmacro{bibindex}%
  \usebibmacro{begentry}%
  \usebibmacro{author/translator+others}%
  \setunit{\labelnamepunct}\newblock
  \usebibmacro{title}%
  \newunit
  \printlist{language}%
  \newunit\newblock
  \usebibmacro{byauthor}%
  \newunit\newblock
  \usebibmacro{in:}%
  \usebibmacro{editor+others}%
  \setunit{\labelnamepunct}\newblock%
  \usebibmacro{maintitle+booktitle}%
  \newunit\newblock
  \usebibmacro{event+venue+date}%
  \newunit\newblock
  \newunit\newblock
  \iffieldundef{maintitle}
    {\printfield{volume}%
     \printfield{part}}
    {}%
  \newunit
  \printfield{volumes}%
  \newunit\newblock
  \usebibmacro{series+number}%
  \newunit\newblock
  \printfield{note}%
  \newunit\newblock
  \printlist{organization}%
  \newunit
  \usebibmacro{publisher+location+date}%
  \newunit\newblock
  \usebibmacro{chapter+pages}%
  \newunit\newblock
  \iftoggle{bbx:isbn}
    {\printfield{isbn}}
    {}%
  \newunit\newblock
  \usebibmacro{doi+eprint+url}%
  \newunit\newblock
  \usebibmacro{addendum+pubstate}%
  \setunit{\bibpagerefpunct}\newblock
  \usebibmacro{pageref}%
  \newunit\newblock
  \iftoggle{bbx:related}
    {\usebibmacro{related:init}%
     \usebibmacro{related}}
    {}%
  \usebibmacro{finentry}}

\renewbibmacro*{journal+issuetitle}{%
  \usebibmacro{journal}%
  \setunit*{\addspace}%
  \iffieldundef{series}
    {}
    {\newunit
     \printfield{series}%
     \setunit{\addspace}}%
% ab hier neu
  \printfield{volume}%
  \setunit{\addspace}%
  \usebibmacro{issue+date}%
  \setunit{\addspace}%
  \printfield{number}% 
  \setunit{\addcomma\space}%
  \printfield{eid}%
%  \usebibmacro{volume+number+eid}%
%  \setunit{\addspace}%
%  \usebibmacro{issue+date}%
% bis hier neu
  \setunit{\addcolon\space}%
  \usebibmacro{issue}%
  \newunit}

\endinput
```

Besonders die `.bbx` geht bestimmt noch etwas eleganter. Vielleicht sehe ich mir das später nochmal an. Ich kann nicht garantieren, dass die Ausgabe allen Kleinigkeiten gleich ist, die Abweichungen sollten aber minimal sein.

Viel Erfolg mit der Dissertation!

**Comment by johannesbottcher** [comment]
@moewew Neuigkeiten bezüglich 3.3 bzw. der Notwendigkeit eines eigenen Stils? vgl. `biblatex-iso` 

Anwenderfall: http://texwelt.de/wissen/fragen/16761/biblatex-gibt-bei-typ-misc-nicht-das-feld-publisher-aus

**Comment by moewew** [comment]
Was Version 3.3 angeht, sollte eigentlich alles gut gehen.

Mich wundert, dass `organization` nicht funktionieren soll, `\DeclareBibliographyDriver{misc}` ruft doch `\usebibmacro{organization+location+date}` auf?

Was die Notwendigkeit eines neuen Stils angeht bin ich mir auch nicht sicher. Es schient mir inzwischen so, dass viele Leute ihre Vorgabe einfach ISO/DIN nennen und den Interpretationsspielraum voll ausnutzen, dann aber auf ihrer bestimmten Vorstellung bestehen. Hinzu kommt noch unterschiedliche regionale Auslegung (siehe `biblatex-iso690` mit der tschechischen Version). Wenn es keine eineindeutigen Vorgaben gibt, sehe ich wenig Sinn darin, einen Stil zu schreiben, der vorgibt "den Vorgaben" zu folgen. Man könnte natürlich versuchen, etablierte BibTeX-(DIN/ISO-)Stile zu portieren (ähnlich wie `biblatex-trad` das tut).

**Comment by johannesbottcher** [comment]
Für mich liegt das Problem im akademischen Umfeld. Wenn ein Betreuer sagt "du muss nach Harvard" zitieren und ein Student sucht sich dumm und dämlich ... Gleiches bei "du musst nach APA zitieren" Im Vergleich zu "Du musst nach DIN zitieren" sind obige ja noch fast eindeutig.

Natürlich trägt der Betreuer keine alleinige Schuld, es muss vorher ansetzen, denn jeder Betreuer war früher auch mal Student. Solang es keine _ordentlichen_ Kurse an den Universitäten bezüglich wissenschaftlicher Arbeiten gibt (was wird zitiert, warum wird zitiert, wie wird zitiert; Warum Einheiten aufrecht, warum geschützte Leerzeichen ...) wird sich das Problem fortsetzen. 

Ich bleibe dabei, wenn ich die ISO richtig deute, dann benötigt man keinen eigenen Stil, welcher die Norm erfüllt.

**Comment by moewew** [comment]
Ja, mit "Leute[n]" oben meinte ich vor allem "Leute, die anderen sagen/vorschreiben können, wie sie zu zitieren haben".

APA-Style ist eigentlich klar vorgegeben, genauso wie Chicago-Stil, bei anderen Begriffen wie Harvard hat man natürlich sofort verloren. Aber dann kann man ja alle Vorgaben noch mit Extrawünschen garnieren und das dann trotzdem APA oder Chicago nennen.

Ich habe die Vorgaben noch immer nicht gelesen, und bin mir daher nicht sicher, ob da nicht doch irgendwelche Vorgaben gemacht werden, die für einen Stil relevant sind (Feldreihenfolge, bestimmte Vorgaben für das Layout des Literaturverzeichnisses, ...). Ich bin aber der Meinung, dass es recht sinnlos ist, einen Stil für "ISO 690" zu implementieren, wenn es einen so großen Interpretationsspielraum gibt, was es geben könnte ist "ISO 690 für Prof. X", aber das ist dann schon sehr speziell.

**Comment by johannesbottcher** [comment]
@moewew  http://infobib.de/2013/12/03/neue-zitier-norm-din-iso-6902013-10/

Am Donnerstag habe ich einen Termin mit der hiesigen Bibliotheksleitung, vielleicht können die ja hinterher ein paar Minuten entbehren und mir eine Meinung/Erklärung geben.

**Comment by domhardt** [comment]
Sry, dass ich mich bisher vornehm aus der Diskussion raushalte. Ich muss im April meine Diss in den Druck geben und bisher erfüllt sogar die aufgeblasene Ursprungsversion die Wünsche meines Doktorvaters (wünscht sich neuerdings "et al." anstelle von "u. a.").

@moewew 
Auch mein Stil ist (m)eine Interpretation der DIN 1505-2 entsprechend den Wünschen meines Doktorvaters sowie die freie Ausgestaltung fehlender Vorgaben. Das wird auch bei einem Stil für die ISO 690 so sein. Ich halte es für legitim, diesen Stil als normkonform zu bezeichnen, solange lediglich der gegebene Interpretationsspielraum ausgenutzt wurde und keine "Verstöße" gegen normative Vorgaben vorhanden sind. Insofern würde ich mich auch über eine Interpretation der DIN ISO 690 (2013) in Form eines BibLaTeX-Stils freuen.

**Comment by domhardt** [comment]
Die gekürzte Version (Vorschlag von @moewew ) scheint ohne Einschränkungen zu funktionieren.

**Comment by moewew** [comment]
Es ist sicher absolut legitim, diesen Stil als DIN-1505-konform zu bezeichnen, wenn er das ist. Was ich für etwas problematischer halte, ist ihn als _den_ DIN-1505-Stil zu verkaufen.

Die Frage ist dann auch, wie sinnvoll es ist, einen "ISO-690-Stil" zu schreiben, wenn die Standardstile schon (fast) die Vorgaben erfüllen.

---

Mit Version 3.3 sind in `biblatex` einige Änderungen im Namensformat vorgenommen worden, dies hat zur Folge, dass einige interne (lower-level) Befehle und auch einige Befehle für den Endbenutzer umbenannt wurden.

Grob gesagt, wurden die Bezeichnungen "last" und "first" bei Namen durch "family" und "given" ersetzt.

Bei Dir betrifft das https://github.com/domhardt/BibLaTeX-DIN1505/blob/master/din.bbx#L18, was nun

```
\DeclareNameAlias{default}{family-given}
```

lauten sollte. (Das sollte aber wegen eines Alias noch funktionieren.)

In Version 3.3 sollte https://github.com/domhardt/BibLaTeX-DIN1505/blob/master/din.bbx#L66 keine Wirkung mehr haben, es sollte zu

```
\renewcommand*{\mkbibnamefamily}[1]{\textsc{#1}}
```

geändert werden. In der kommenden Version 3.4 gibt es Code für erweiterte Abwärtskompatibilität bei Nutzung der alten `\mkbibname...`-Befehle.

**Comment by domhardt** [comment]
@moewew Ich brauche Hilfe!
Ich habe gerade bei mir lokal die vorgeschlagenen Änderungen vorgenommen und BibLaTeX auf Version 3.3 aktualisiert. Jetzt produziert ein Durchlauf von PDFLaTeX folgende Fehlermeldung:

/usr/local/texlive/2015/texmf-dist/tex/latex/biblatex/biblatex.sty
Package: biblatex 2016/03/03 v3.3 programmable bibliographies (PK/JW/AB)
! LaTeX Error: File `biblatex_.sty' not found.

Doch die Datei /usr/local/texlive/2015/texmf-dist/tex/latex/biblatex/biblatex_.sty existiert genauso wie die biblatex.sty im gleichen Ordner.

Die Fehlermeldung verweist auf Zeile  80 der biblatex.sty:
https://github.com/plk/biblatex/blob/dev/tex/latex/biblatex/biblatex.sty#L80

Danke & LG

![bildschirmfoto 2016-03-23 um 13 33 52](https://cloud.githubusercontent.com/assets/1955290/13985256/fb400b12-f0fb-11e5-83aa-33134904531a.png)

EDIT Typo

**Comment by moewew** [comment]
Hast Du `biblatex` manuell aktualisiert? Eventuell musst Du noch texhash laufen lassen (http://albertskblog.blogspot.de/2010/01/locations-of-mactex-files.html). Siehe aber auch https://www.tug.org/mactex/elcapitan.html

**Comment by domhardt** [comment]
@moewew 
Danke für die schnelle Antwort. Habe das Problem nach der ersten Panik in den Griff bekommen. TeX Live Utility hatte zwar BibLaTeX bereits aktualisiert, lief aber noch im Hintergrund und war mit anderen Updates beschäftigt. Das notwendige texhash führt es offensichtlich erst zum Ende aus. Jetzt geht alles wieder und ich habe den aktualisierten DIN-Stil mit Deinen Änderungen gepusht.

Ich habe noch die folgende Warning:

Package biblatex Warning: 'firstinits' option is deprecated, use 'giveninits' i
nstead.

Das liegt aber vermutlich nicht an meinem Stil.

**Comment by moewew** [comment]
Ja die Warnung kommt, da `firstinits` jetzt `giveninits` heißt (siehe die Faustregel oben). Der Stil setzt das nicht, soweit ich sehe, also machst Du das im Dokument selbst. Wenn Du `firstinits` durch `giveninits` ersetzt, gibt es keine Warnung mehr.

**Comment by domhardt** [comment]
Danke für den Tipp. Ich habe es in meiner Optionen.tex gefunden. Jetzt läuft es ohne Warnungen. Vielen Dank für Deine Hilfe.
