### ISSUE TITLE
Zitat im Text lautet "Autor1 & Autor2 u. a. (JAHR)" statt "Autor1 u. a. (JAHR)"

### ISSUE THREAD

**Issue by domhardt** [domhardt/BibLaTeX-DIN1505#2]
\textcite{Wickens2004} wird zu "Wickens & Gordon-Becker u. a. (2004)", richtig wäre "Wickens u. a. (2004)", bib-Eintrag ist korrekt.

\parencite{Beck2015} wird zu "(Beck & Ye u.a. 2015)", richtig wäre "(Beck u.a. 2015)", bib-Eintrag ist korrekt.

_Bib-Einträge_

@Book{Wickens2004,
  Title                    = {An Introduction to Human Factors Engineering},
  Author                   = {Christopher D. Wickens and Sallie E. Gordon-Becker and Yili Liu and John Lee},
  Edition                  = {2},
  ISBN                     = {978-0131837362},
  Publisher                = {Pearson Prentice Hall},
  Address                  = {New Jersey},
  Date                     = {2004}
}

@Article{Beck2015,
  Title                    = {Local muscle endurance is associated with fatigue-based changes in electromyographic spectral properties, but not with conduction velocity},
  Author                   = {Travis W. Beck and Xin Ye and Nathan P. Wages},
  Date                     = {2015},
  Journaltitle             = {Journal of Electromyography and Kinesiology},
  Doi                      = {10.1016/j.jelekin.2015.02.006},
  ISSN                     = {1050-6411},
  Number                   = {3},
  Pages                    = {451-456},
  Volume                   = {25}
}

_BibLaTeX-Aufruf_
\usepackage[%       Bibliografiestil für BibLaTeX
style=din%
%, firstinits%
, natbib=true%
, sorting=nyt%
%, maxnames=2%      Festlegung von BibNames und CiteNames
, maxcitenames=1%   Kürzel im Text nur aus 2 Autoren
, maxbibnames=99%   alle Autoren im Literaturverzeichnis (kein et al.)
, uniquename=false% Keine Initialen bei identischen Namen
, backend=biber%        (bibtex, biber)
, bibencoding=utf8% Zeichenkodierung der Bib-Datei
, bibwarn=true%     Warnung bei fehlerhafter bib-Datei
%, mincrossrefs=1%
, isbn=false%
%, url=false%
%, doi=false%
%, eprint=false%
]{biblatex}

**Comment by moewew** [comment]
Da ich das Problem nicht reproduzieren kann, gehe ich davon aus, dass das mit `uniquelist` zu tun hat. Die Option `, uniquelist=false` sollte also Abhilfe schaffen.

Hintergründe dazu gibt es bei TeX.SX

http://tex.stackexchange.com/q/251285/35864
http://tex.stackexchange.com/q/69028/35864
http://tex.stackexchange.com/q/17838/35864
http://tex.stackexchange.com/q/67033/35864
http://tex.stackexchange.com/q/67961/35864

**Comment by domhardt** [comment]
Die Option "uniquelist=false" behebt dieses Problem. Danke an @moewew für den Tipp.
Der Aufruf für BibLaTeX sieht daher jetzt so aus:

BibLaTeX-Aufruf

``` latex
\usepackage[% Bibliografiestil für BibLaTeX
style=din%
%, firstinits%
, natbib=true%
, sorting=nyt%
%, maxnames=2% Festlegung von BibNames und CiteNames
, maxcitenames=2% Kürzel im Text nur aus 2 Autoren
, maxbibnames=99% alle Autoren im Literaturverzeichnis (kein et al.)
, uniquename=false% Keine Initialen bei identischen Namen
, backend=biber% (bibtex, biber)
, bibencoding=utf8% Zeichenkodierung der Bib-Datei
, bibwarn=true% Warnung bei fehlerhafter bib-Datei
%, mincrossrefs=1%
, isbn=false%
%, url=false%
%, doi=false%
%, eprint=false%
, uniquelist=false% verhindert zusätzliche Namen bei Zitaten im Text
]{biblatex}
```
